### ISSUE TITLE
Update installation instructions for Steam and EA app

### ISSUE THREAD

**Issue by VanillaCold** [Spore-Community/ModBrowser#13]
The mod installation instruction page still says that there are issues running mods on Steam Spore, in spite of the fix for Steam Spore that was released recently for the Spore ModAPI Launcher Kit.

**Comment by Kade-N** [comment]
Also need to add EA app information

**Comment by Kade-N** [comment]
Updated the Installation page 7b6ba736660a7a8aaa3ad3d6f1014e6273c3ee91 and Get Spore page 4ee0933d0577d2828f119e8d98f0fcccb55f6c38 to reflect Steam and EA app
